# -*- coding: utf-8 -*-
from pathlib import Path

lines = [
    '{% extends "base.html" %}',
    "{% set active = 'pick' %}",
    "{% block body %}",
    '<section class="hero">',
    '  <span class="badge">{{ time_window }} \u00b7 {{ keywords }}</span>',
    "  <h1>\u9009\u62e9\u5a92\u4f53</h1>",
    "  <p class=\"lead\">\u52fe\u9009\u5a92\u4f53\uff08\u53ef\u591a\u9009\uff09\uff0c\u6293\u53d6\u8fc7\u53bb 24 \u5c0f\u65f6\u5185\u4e2d\u56fd\u76f8\u5173\u65b0\u95fb\u5e76\u663e\u793a\u4e2d\u6587\u7ffb\u8bd1\u3002</p>",
    "</section>",
    "",
    "{% with messages = get_flashed_messages(with_categories=true) %}",
    "  {% for cat, msg in messages %}",
    '  <div class="flash {{ cat }}">{{ msg }}</div>',
    "  {% endfor %}",
    "{% endwith %}",
    "",
    '<form method="post" id="fetch">',
    '  <motion class="card">',
    '    <div class="pick-toolbar">',
    "      <h2>5 \u5bb6\u5a92\u4f53</h2>",
    '      <p class="pick-count" id="pick-count">\u5df2\u9009 0 / {{ catalog|length }}</p>',
    "    </div>",
    '    <div class="pick-actions">',
    '      <button type="button" class="btn btn-ghost btn-sm" id="btn-all">\u5168\u9009</button>',
    '      <button type="button" class="btn btn-ghost btn-sm" id="btn-none">\u5168\u4e0d\u9009</button>',
    "    </div>",
    '    <div class="media-grid" role="group" aria-label="\u5a92\u4f53\u5217\u8868">',
    "      {% for m in catalog %}",
    '      <label class="media-item media-check">',
    '        <input type="checkbox" class="media-cb" name="media" value="{{ m.key }}" {% if m.key in selected %}checked{% endif %}>',
    '        <span class="check-ui" aria-hidden="true"></span>',
    '        <div class="media-body">',
    '          <div class="media-name"><span class="pill">{{ m.country }}</span>{{ m.name }}</div>',
    '          <div class="media-sub">{{ m.domain }}</motion>',
    "        </div>",
    "      </label>",
    "      {% endfor %}",
    "    </div>",
    '    <div class="btn-row" style="margin-top:16px">',
    '      <button type="submit" class="btn btn-primary btn-block">\u4fdd\u5b58\u9009\u62e9</button>',
    '      <a class="btn btn-ghost" href="{{ url_for(\'clear_pick\') }}">\u6e05\u7a7a</a>',
    "    </div>",
    "  </div>",
    "</form>",
    "",
    "<script>",
    "(function () {",
    "  var boxes = document.querySelectorAll('.media-cb');",
    "  var countEl = document.getElementById('pick-count');",
    "  function updateCount() {",
    "    var n = 0;",
    "    boxes.forEach(function (b) { if (b.checked) n += 1; });",
    "    countEl.textContent = '\\u5df2\\u9009 ' + n + ' / ' + boxes.length;",
    "  }",
    "  boxes.forEach(function (b) { b.addEventListener('change', updateCount); });",
    "  document.getElementById('btn-all').addEventListener('click', function () {",
    "    boxes.forEach(function (b) { b.checked = true; }); updateCount();",
    "  });",
    "  document.getElementById('btn-none').addEventListener('click', function () {",
    "    boxes.forEach(function (b) { b.checked = false; }); updateCount();",
    "  });",
    "  updateCount();",
    "})();",
    "</script>",
    "{% endblock %}",
]
text = "\n".join(lines).replace("<motion", "<div").replace("</motion>", "</div>")
Path(__file__).resolve().parent.parent.joinpath("templates", "pick.html").write_text(
    text, encoding="utf-8"
)
print("ok")
